---
title: "Could Boston Reduce Police Payroll Through Additional Hires?"
output: html_notebook
---

```{r warning = FALSE, echo = FALSE, results = 'hide', message = FALSE}
#loading libraries
library(tidyverse)

#load in data
data <- read_csv('https://data.boston.gov/dataset/418983dc-7cae-42bb-88e4-d56f5adcf869/resource/70129b87-bd4e-49bb-aa09-77644da73503/download/employee-earnings-report-2017.csv', col_names = T)

#retain only columns needed for analyses
data <- data %>%
          select(`DEPARTMENT NAME`, TITLE, REGULAR, OVERTIME)
data

#regular and overtime pay are characters and in accounting notation, so change to numeric
data <- data %>%
  mutate(REGULAR = str_replace_all(REGULAR, "[$,)]", ""), OVERTIME = str_replace_all(OVERTIME, "[$,)]", "")) %>%
  mutate(REGULAR = as.numeric(str_replace(REGULAR, "[(]", "-")), OVERTIME = as.numeric(str_replace(OVERTIME, "[(]", "-"))) %>%
  mutate(TITLE = as.factor(TITLE), `DEPARTMENT NAME` = as.factor(`DEPARTMENT NAME`)) %>%
  rename(dept_name = `DEPARTMENT NAME`)

data
```

```{r}
##calculate total regular and OT pay
total_payroll <- sum(data['REGULAR'], na.rm = T)
total_overtime <- sum(data['OVERTIME'], na.rm = T)
  
##calculate regular and OT pay (and percentage) for each department
pay_by_dept <- data %>%
                  group_by(dept_name) %>%
                  summarize(tot_regular = sum(REGULAR, na.rm = T), percent_regular = round(100*(tot_regular/total_payroll),2), tot_overtime = sum(OVERTIME, na.rm = T), percent_overtime = round(100*(tot_overtime/total_overtime),2))

#put data into long form for graphing
pay_percentages <- pay_by_dept %>%
                      select(dept_name, percent_regular, percent_overtime) %>%
                      filter(percent_overtime >= 1) %>%
                      gather(key = percent, values = c('percent_regular', 'percent_overtime'))


ggplot(data = pay_percentages, aes(x = dept_name, y = value, fill = factor(percent, labels = c('Overtime', 'Regular')))) +
  geom_bar(stat = 'identity', position = position_dodge()) +
  labs(y = 'Percentage', title = 'Percentage of Regular and Overtime Pay by Department', fill = 'Pay Type') +
  theme(axis.title.y = element_blank()) +
  scale_fill_brewer(palette="Paired")+
  coord_flip() 


##select only police dpt data
data_police <- data %>%
                filter(dept_name == 'Boston Police Department')
```

```{r  warning = FALSE}
#create hourly rates and OT hours, assuming 40 work week, 52 weeks per year, 1.5 pay for OT
data_police <- data_police %>%
                  mutate(hourly_rate = REGULAR/(40*52), hours_overtime = OVERTIME/(hourly_rate*1.5))

#Minimum wage in MA is $11, so exclude those with hourly rates less than $11 (likely either part time or mid-year hires, making hours of overtime worked incorrect)
data_police <- data_police %>%
                  filter(hourly_rate >= 11)

##determine the 
top4OTpositions <- (data_police %>%
                      group_by(TITLE) %>%
                      summarize(number_employees = n(), total_OT_hours = sum(hours_overtime, na.rm = T), total_overtime_pay = sum(OVERTIME, na.rm = T)) %>%
                      top_n(4, wt = total_OT_hours) %>%
                      select(TITLE))[[1]]

top4OT_data <- data_police %>%
                  filter(TITLE %in% top4OTpositions)

ggplot(top4OT_data, aes(x = hours_overtime, color = TITLE)) +
  geom_density() +
  labs(title = 'Overtime Hours Density Curve for \n Positions with Most Overtime', x = 'Overtime Hours', y = 'Density', color = 'Job') +
  theme(plot.title = element_text(hjust=0.5))
```


```{r}
##Number of employees per job with over average 20 hours of overtime a week
hours_by_title <- data_police %>%
                      group_by(TITLE) %>%
                      filter(hours_overtime >= (52*20)) %>%
                      summarize(n = n(), total_hours = sum(hours_overtime), total_overtime_pay = sum(OVERTIME))

##number of employees required to cover those hours
hours_by_title <- hours_by_title %>%
                      mutate(new_employees = floor(total_hours/(52*40)), leftover_hours = total_hours - new_employees*(52*40)) %>%
                      filter(n > 1)

##median salary of employees by title
median_salaries <- data_police %>%
                      group_by(TITLE) %>%
                      summarize(median_salary = median(REGULAR))

##join tibbles
hours_by_title <- inner_join(hours_by_title, median_salaries, by = 'TITLE')

##calculate pay saving
hours_by_title <- hours_by_title %>%
                    mutate(pay_savings = total_overtime_pay - median_salary*new_employees - leftover_hours*(1.5*median_salary/2080))

total_savings <- sum(hours_by_title[['pay_savings']])
```


